import { Gift } from "./types";

export const hobbies = [
  "Viaggi",
  "Moda",
  "Cucina",
  "Videogiochi",
  "Giardinaggio",
  "Musica",
  "Sport",
  "Cinema",
  "Avventura",
  "Letteratura",
  "Enologia",
  "Arte",
  "Campeggio",
  "Fotografia",
  "Tecnologia",
  "Sport Acquatici",
  "Escursionismo",
  "Giochi da tavolo",
];

export const gifts: Array<Gift> = [
  {
    name: "Weekend romantico",
    relation: ["Partner Romantico"],
    hobby: "Viaggi",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Gioielli personalizzati",
    relation: [
      "Partner Romantico",
      "Amica/o",
      "Figlia/o",
      "Genitore",
      "Sorella/Fratello",
    ],
    hobby: "Moda",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Cena gourmet a casa",
    relation: ["Partner Romantico"],
    hobby: "Cucina",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Abbonamento a una scuola di cucina",
    relation: [
      "Partner Romantico",
      "Amica/o",
      "Figlia/o",
      "Genitore",
      "Sorella/Fratello",
    ],
    hobby: "Cucina",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Serata spa per due",
    relation: ["Partner Romantico"],
    hobby: "Viaggi",
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Nuova console di gioco",
    relation: ["Figlia/o", "Partner Romantico"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 30,
  },
  {
    name: "Cuffie gaming di alta qualità",
    relation: ["Figlia/o", "Partner Romantico", "Sorella/Fratello"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 30,
  },
  {
    name: "Maglietta personalizzata",
    relation: ["Figlia/o", "Partner Romantico", "Sorella/Fratello"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 30,
  },
  {
    name: "Libro d'arte sui videogiochi",
    relation: ["Figlia/o", "Amica/o"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 21,
  },
  {
    name: "Tappetino mouse XXL",
    relation: ["Figlia/o", "Partner Romantico", "Amica/o"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 30,
  },

  {
    name: "Set di attrezzi da giardino",
    relation: [
      "Genitore",
      "Partner Romantico",
      "Sorella/Fratello",
      "Sorella/Fratello",
    ],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Corso di giardinaggio",
    relation: ["Genitore", "Amica/o", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Nuove piante o fiori",
    relation: ["Genitore", "Amica/o", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Compostiera di design",
    relation: ["Genitore", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Libro illustrato di giardinaggio",
    relation: ["Genitore", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Abbonamento a uno streaming musicale",
    relation: ["Sorella/Fratello", "Amica/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Cuffie wireless di fascia alta",
    relation: ["Sorella/Fratello", "Partner Romantico", "Figlia/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Biglietti per un concerto",
    relation: ["Sorella/Fratello", "Figlia/o", "Partner Romantico"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Lezioni di musica online",
    relation: ["Sorella/Fratello", "Amica/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Poster artistico",
    relation: ["Sorella/Fratello", "Figlia/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },

  {
    name: "Kit per l'allenamento a casa",
    relation: ["Sorella/Fratello", "Partner Romantico"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Maglietta personalizzata della squadra",
    relation: ["Sorella/Fratello", "Amica/o", "Figlia/o"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Scarpe da corsa di alta qualità",
    relation: ["Sorella/Fratello", "Partner Romantico"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Biglietti per una partita",
    relation: ["Sorella/Fratello", "Partner Romantico", "Amica/o"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Abbonamento a una rivista sportiva",
    relation: ["Sorella/Fratello", "Genitore"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },

  {
    name: "Abbonamento a un servizio di streaming per film",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Proiettore portatile",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Set di popcorn gourmet",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Poster cinematografico",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Esperienza di volo in mongolfiera",
    relation: ["Partner Romantico"],
    hobby: "Avventura",
    minAge: 21,
    maxAge: Infinity,
  },
  {
    name: "Corso di pittura a olio",
    relation: ["Amica/o", "Figlia/o", "Sorella/Fratello"],
    hobby: "Arte",
    minAge: 15,
    maxAge: Infinity,
  },
  {
    name: "Voucher per una degustazione di vini",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Enologia",
    minAge: 21,
    maxAge: Infinity,
  },
  {
    name: "Set di pennelli artistici di alta qualità",
    relation: ["Figlia/o", "Amica/o", "Sorella/Fratello"],
    hobby: "Arte",
    minAge: 12,
    maxAge: Infinity,
  },
  {
    name: "Libro di cucina internazionale",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cucina",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Tour gastronomico in una città famosa",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Cucina",
    minAge: 25,
    maxAge: Infinity,
  },
  {
    name: "Attrezzatura da campeggio di alta qualità",
    relation: ["Figlia/o", "Sorella/Fratello", "Amica/o"],
    hobby: "Campeggio",
    minAge: 16,
    maxAge: Infinity,
  },
  {
    name: "Lezioni di fotografia",
    relation: ["Figlia/o", "Amica/o", "Sorella/Fratello"],
    hobby: "Fotografia",
    minAge: 14,
    maxAge: Infinity,
  },
  {
    name: "Abbonamento a una rivista di tecnologia",
    relation: ["Figlia/o", "Sorella/Fratello"],
    hobby: "Tecnologia",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Esperienza di immersione subacquea",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Sport Acquatici",
    minAge: 21,
    maxAge: Infinity,
  },
  {
    name: "Escursione in mongolfiera al tramonto",
    relation: ["Partner Romantico"],
    hobby: "Avventura",
    minAge: 25,
    maxAge: Infinity,
  },
  {
    name: "Corso di scrittura creativa",
    relation: ["Amica/o", "Figlia/o", "Sorella/Fratello"],
    hobby: "Letteratura",
    minAge: 16,
    maxAge: Infinity,
  },
  {
    name: "Voucher per una serata di degustazione di cioccolato",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Cioccolato",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Set di pennelli per acquerelli di lusso",
    relation: ["Figlia/o", "Amica/o", "Sorella/Fratello"],
    hobby: "Arte",
    minAge: 14,
    maxAge: Infinity,
  },
  {
    name: "Libro di ricette di pasticceria",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cucina",
    minAge: 20,
    maxAge: Infinity,
  },
  {
    name: "Tour enogastronomico in una regione vinicola",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Cucina",
    minAge: 30,
    maxAge: Infinity,
  },
  {
    name: "Zaino da trekking di alta qualità",
    relation: ["Figlia/o", "Sorella/Fratello", "Amica/o"],
    hobby: "Escursionismo",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Corso avanzato di fotografia notturna",
    relation: ["Figlia/o", "Amica/o", "Sorella/Fratello"],
    hobby: "Fotografia",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Abbonamento a una rivista di innovazione tecnologica",
    relation: ["Figlia/o", "Sorella/Fratello"],
    hobby: "Tecnologia",
    minAge: 20,
    maxAge: Infinity,
  },
  {
    name: "Escursione guidata di snorkeling",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Sport Acquatici",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Set di ceramiche fai-da-te",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Arte",
    minAge: 16,
    maxAge: Infinity,
  },
  {
    name: "Voucher per una lezione di cucina gourmet",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Cucina",
    minAge: 25,
    maxAge: Infinity,
  },
  {
    name: "Tenda da campeggio ultraleggera",
    relation: ["Figlia/o", "Sorella/Fratello", "Amica/o"],
    hobby: "Campeggio",
    minAge: 20,
    maxAge: Infinity,
  },
  {
    name: "Corso online di fotografia paesaggistica",
    relation: ["Figlia/o", "Amica/o", "Sorella/Fratello"],
    hobby: "Fotografia",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Giochi da tavolo di strategia",
    relation: ["Figlia/o", "Sorella/Fratello", "Amica/o"],
    hobby: "Giochi da tavolo",
    minAge: 12,
    maxAge: Infinity,
  },
  {
    name: "Lezioni di surf",
    relation: ["Partner Romantico", "Amica/o"],
    hobby: "Sport Acquatici",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Quadro personalizzato",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Arte",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Kit di attrezzi da giardino per principianti",
    relation: ["Genitore", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 14,
    maxAge: Infinity,
  },
  {
    name: "Voucher per una serata musicale dal vivo",
    relation: ["Sorella/Fratello", "Amica/o"],
    hobby: "Musica",
    minAge: 18,
    maxAge: 30,
  },
  {
    name: "Escursione in montagna con guida",
    relation: ["Sorella/Fratello", "Partner Romantico"],
    hobby: "Escursionismo",
    minAge: 18,
    maxAge: Infinity,
  },
];
