import { Gift } from "./types";

export const gifts: Array<Gift> = [
  {
    name: "Weekend romantico",
    relation: ["Partner Romantico"],
    hobby: ["Viaggi"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Gioielli personalizzati",
    relation: ["Partner Romantico"],
    hobby: ["Moda"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Cena gourmet a casa",
    relation: ["Partner Romantico"],
    hobby: ["Cucina"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Abbonamento a una scuola di cucina",
    relation: ["Partner Romantico"],
    hobby: ["Cucina"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Serata spa per due",
    relation: ["Partner Romantico"],
    hobby: ["Viaggi"],
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Nuova console di gioco",
    relation: ["Figlio", "Figlia"],
    hobby: ["Videogiochi"],
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Cuffie gaming di alta qualità",
    relation: ["Figlio", "Figlia"],
    hobby: ["Videogiochi"],
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Maglietta personalizzata",
    relation: ["Figlio", "Figlia"],
    hobby: ["Videogiochi"],
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Libro d'arte sui videogiochi",
    relation: ["Figlio", "Figlia"],
    hobby: ["Videogiochi"],
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Tappetino mouse XXL",
    relation: ["Figlio", "Figlia"],
    hobby: ["Videogiochi"],
    minAge: 10,
    maxAge: 15,
  },

  {
    name: "Set di attrezzi da giardino",
    relation: ["Genitore"],
    hobby: ["Giardinaggio"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Corso di giardinaggio",
    relation: ["Genitore"],
    hobby: ["Giardinaggio"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Nuove piante o fiori",
    relation: ["Genitore"],
    hobby: ["Giardinaggio"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Compostiera di design",
    relation: ["Genitore"],
    hobby: ["Giardinaggio"],
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Libro illustrato di giardinaggio",
    relation: ["Genitore"],
    hobby: ["Giardinaggio"],
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Abbonamento a uno streaming musicale",
    relation: ["Sorella"],
    hobby: ["Musica"],
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Cuffie wireless di fascia alta",
    relation: ["Sorella"],
    hobby: ["Musica"],
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Biglietti per un concerto",
    relation: ["Sorella"],
    hobby: ["Musica"],
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Lezioni di musica online",
    relation: ["Sorella"],
    hobby: ["Musica"],
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Poster artistico",
    relation: ["Sorella"],
    hobby: ["Musica"],
    minAge: 20,
    maxAge: 25,
  },

  {
    name: "Kit per l'allenamento a casa",
    relation: ["Fratello"],
    hobby: ["Sport"],
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Maglietta personalizzata della squadra",
    relation: ["Fratello"],
    hobby: ["Sport"],
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Scarpe da corsa di alta qualità",
    relation: ["Fratello"],
    hobby: ["Sport"],
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Biglietti per una partita",
    relation: ["Fratello"],
    hobby: ["Sport"],
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Abbonamento a una rivista sportiva",
    relation: ["Fratello"],
    hobby: ["Sport"],
    minAge: 25,
    maxAge: 30,
  },

  {
    name: "Abbonamento a un servizio di streaming per film",
    relation: ["Amico"],
    hobby: ["Cinema"],
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Proiettore portatile",
    relation: ["Amico"],
    hobby: ["Cinema"],
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Set di popcorn gourmet",
    relation: ["Amico"],
    hobby: ["Cinema"],
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Poster cinematografico",
    relation: ["Amico"],
    hobby: ["Cinema"],
    minAge: 30,
    maxAge: 35,
  },
];
