import { Gift } from "./types";

export const gifts: Array<Gift> = [
  {
    name: "Weekend romantico",
    relation: ["Partner Romantico"],
    hobby: "Viaggi",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Gioielli personalizzati",
    relation: ["Partner Romantico", "Amica/o", "Figlia/o", "Genitore", "Sorella/Fratello"],
    hobby: "Moda",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Cena gourmet a casa",
    relation: ["Partner Romantico"],
    hobby: "Cucina",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Abbonamento a una scuola di cucina",
    relation: ["Partner Romantico", "Amica/o", "Figlia/o", "Genitore", "Sorella/Fratello"],
    hobby: "Cucina",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Serata spa per due",
    relation: ["Partner Romantico"],
    hobby: "Viaggi",
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Nuova console di gioco",
    relation: ["Figlia/o", "Partner Romantico"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Cuffie gaming di alta qualità",
    relation: ["Figlia/o", "Partner Romantico", "Sorella/Fratello"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Maglietta personalizzata",
    relation: ["Figlia/o", "Partner Romantico", "Sorella/Fratello"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Libro d'arte sui videogiochi",
    relation: ["Figlia/o", "Partner Romantico", "Amica/o"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 15,
  },
  {
    name: "Tappetino mouse XXL",
    relation: ["Figlia/o", "Partner Romantico", "Amica/o"],
    hobby: "Videogiochi",
    minAge: 10,
    maxAge: 15,
  },

  {
    name: "Set di attrezzi da giardino",
    relation: ["Genitore", "Partner Romantico", "Sorella/Fratello", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Corso di giardinaggio",
    relation: ["Genitore", "Amica/o", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Nuove piante o fiori",
    relation: ["Genitore", "Amica/o", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Compostiera di design",
    relation: ["Genitore", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },
  {
    name: "Libro illustrato di giardinaggio",
    relation: ["Genitore", "Sorella/Fratello"],
    hobby: "Giardinaggio",
    minAge: 18,
    maxAge: Infinity,
  },

  {
    name: "Abbonamento a uno streaming musicale",
    relation: ["Sorella/Fratello", "Amica/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Cuffie wireless di fascia alta",
    relation: ["Sorella/Fratello", "Partner Romantico", "Figlia/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Biglietti per un concerto",
    relation: ["Sorella/Fratello", "Figlia/o", "Partner Romantico"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Lezioni di musica online",
    relation: ["Sorella/Fratello", "Amica/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },
  {
    name: "Poster artistico",
    relation: ["Sorella/Fratello", "Figlia/o"],
    hobby: "Musica",
    minAge: 20,
    maxAge: 25,
  },

  {
    name: "Kit per l'allenamento a casa",
    relation: ["Sorella/Fratello", "Partner Romantico"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Maglietta personalizzata della squadra",
    relation: ["Sorella/Fratello", "Amica/o", "Figlia/o"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Scarpe da corsa di alta qualità",
    relation: ["Sorella/Fratello", "Partner Romantico"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Biglietti per una partita",
    relation: ["Sorella/Fratello", "Partner Romantico", "Amica/o"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },
  {
    name: "Abbonamento a una rivista sportiva",
    relation: ["Sorella/Fratello", "Genitore"],
    hobby: "Sport",
    minAge: 25,
    maxAge: 30,
  },

  {
    name: "Abbonamento a un servizio di streaming per film",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Proiettore portatile",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Set di popcorn gourmet",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
  {
    name: "Poster cinematografico",
    relation: ["Amica/o", "Sorella/Fratello"],
    hobby: "Cinema",
    minAge: 30,
    maxAge: 35,
  },
];
